# Generated by Django 5.0.4 on 2024-05-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("p1App", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectdb",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
