# Generated by Django 4.1.5 on 2024-05-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdb',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdb',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
