# Generated by Django 4.1.5 on 2024-05-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserdb',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuserdb',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuserdb',
            name='web',
            field=models.URLField(blank=True),
        ),
    ]
