# Generated by Django 5.0.4 on 2024-05-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("p1App", "0002_alter_projectdb_active"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Messagedb",
        ),
    ]
