# Generated by Django 4.1.5 on 2024-05-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1App', '0002_projectdb_date_projectdb_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdb',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_files'),
        ),
    ]
