# Generated by Django 4.1.5 on 2024-05-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1App', '0002_alter_customuserdb_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserdb',
            name='Location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='customuserdb',
            name='country',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='customuserdb',
            name='designation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuserdb',
            name='proff_bio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
