# Generated by Django 4.1.5 on 2024-05-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p1App', '0003_alter_customuserdb_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserdb',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuserdb',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='customuserdb',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuserdb',
            name='web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
